using System.Collections.Generic;

namespace Reccomender.DataStructures
{
    public class HobbyEnum
    {
        public Dictionary<int, string> hobbies = new Dictionary<int, string>()
        {
            {1,"Art" },
            {2,"Math" },
            {3,"Urban Planning" },
            {4,"Science" },
            {5,"Music" },
            {6,"Algebra" },
            {7,"Geometry" },
            {8,"Programming" },
            {9,"Robotics" },
            {10,"Sport" },
            {11,"Biotechnology" },
            {12,"Energetics" },
            {13,"Software" },
            {14,"Architecture" },
            {15,"Mechanics" },
            {16,"Management" },
            {17,"Economy" },
            {18,"Textile" },
            {19,"Clothing" },
            {20,"Machines" },
            {21,"Sewing" },
            {22,"Cooking" },
            {23,"Baking" },
            {24,"Driving" },
            {25,"Engineering" },
            {26,"Transport" },
            {27,"Communication" },
            {28,"Radio" },
            {29,"Computers" },
            {30,"Biomedicine" },
            {31,"Chemistry" },
            {32,"Design" },
            {33,"Right" },
            {34,"Law" },
            {35,"Construction" },
            {36,"Woodworking" },
            {37,"Politics" },
            {38,"Society" },
            {39,"Citizenship" },
            {40,"Geography" },
            {41,"Realty" },
            {42,"Accounting" },
            {43,"Marketing" },
            {44,"Business" },
            {45,"Administration" },
            {46,"Energy" },
            {47,"Industrial" },
            {48,"Analytics" },
            {49,"Training" },
            {50,"Leadership" },
        };
    }
}
