// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Unipply.Context;

namespace Unipply.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220502155541_SeedSpecialtyDataTable")]
    partial class SeedSpecialtyDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Unipply.Models.FacultyData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FacultyData");
                });

            modelBuilder.Entity("Unipply.Models.SpecialtyData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SpecialtyData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("901a4f48-967b-4963-aff6-f7477e12466a"),
                            Description = "Short Description",
                            FacultyId = new Guid("f6aa4c0e-edc2-4bad-a22b-8516e3637546"),
                            Title = "Engineering and management in Energetics"
                        },
                        new
                        {
                            Id = new Guid("e64d5245-a443-441e-a970-a44d043639fd"),
                            Description = "Short Description",
                            FacultyId = new Guid("f6aa4c0e-edc2-4bad-a22b-8516e3637546"),
                            Title = "Electroenergetics"
                        },
                        new
                        {
                            Id = new Guid("a10387f7-d2d1-45f8-84a4-f33c25414140"),
                            Description = "Short Description",
                            FacultyId = new Guid("f6aa4c0e-edc2-4bad-a22b-8516e3637546"),
                            Title = "Thermoenergetics"
                        },
                        new
                        {
                            Id = new Guid("aea06a0f-15de-4bb7-a5d1-2338a4421ddb"),
                            Description = "Short Description",
                            FacultyId = new Guid("f6aa4c0e-edc2-4bad-a22b-8516e3637546"),
                            Title = "Engineering and Quality Management"
                        },
                        new
                        {
                            Id = new Guid("b2f39374-44a0-422d-8f67-4718aca12779"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Engineering and industrial technologies"
                        },
                        new
                        {
                            Id = new Guid("21a081bd-84fb-48d2-93ac-ca9a4051fa08"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Transport Engineering and Management"
                        },
                        new
                        {
                            Id = new Guid("86fd7637-a499-4fd9-8664-370b52809125"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Technology of car construction"
                        },
                        new
                        {
                            Id = new Guid("d03eb219-6767-40b7-aa52-1cb4dcfe2eff"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Machinery and Production Systems"
                        },
                        new
                        {
                            Id = new Guid("0edaee5b-9836-440b-9706-ccbe62e412a4"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Mechanical engineering"
                        },
                        new
                        {
                            Id = new Guid("ea7b1962-dbc9-4c19-9029-c915e175bcf0"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Machinery and Refrigerating installations, air-conditioning systems"
                        },
                        new
                        {
                            Id = new Guid("c6dd205b-dde3-4688-9441-caa671ae9a55"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Product design engineering"
                        },
                        new
                        {
                            Id = new Guid("20366fc8-5355-4947-b629-4ce5dc30877d"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Industrial Design"
                        },
                        new
                        {
                            Id = new Guid("f6a7db95-5a83-47fb-a49a-fb794912af80"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Motor Transport Engineering"
                        },
                        new
                        {
                            Id = new Guid("8862bffd-e76b-476d-a052-1744911d2486"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Rail transport engineering"
                        },
                        new
                        {
                            Id = new Guid("eae0c50c-2ea4-43d3-b3fb-a885e7c19f3e"),
                            Description = "Short Description",
                            FacultyId = new Guid("78050741-da48-451d-bdc7-e05031aa724e"),
                            Title = "Transport and shipping services"
                        },
                        new
                        {
                            Id = new Guid("f90c4804-2743-487c-aece-3aea8015779e"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Interior Design"
                        },
                        new
                        {
                            Id = new Guid("4a48e042-5a06-4e58-a456-2a89334a147f"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Sculpture"
                        },
                        new
                        {
                            Id = new Guid("3fb02bd3-a8a2-41e2-99ea-ca574de5108e"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Environmental engineering"
                        },
                        new
                        {
                            Id = new Guid("21adc284-960b-408a-b66e-5d4d8e05cdb9"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Mechanical Engineering in Construction"
                        },
                        new
                        {
                            Id = new Guid("deca6746-63a3-4da7-b9cd-4f6ba6089d1d"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Engineering of construction materials and fittings"
                        },
                        new
                        {
                            Id = new Guid("a9987eca-dbf6-4cb7-ba5c-aa663e0728a4"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Architecture"
                        },
                        new
                        {
                            Id = new Guid("edba02e7-d8af-408d-9dee-8da99af6c8a7"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Urban planning and landscape management"
                        },
                        new
                        {
                            Id = new Guid("d1e70abd-b0f5-40a9-b1f2-894fbfb50fb3"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Landscape architecture and green spaces"
                        },
                        new
                        {
                            Id = new Guid("5a9e55e7-555f-4786-aaf0-aba6c2640a92"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Railways. Roads and Bridges"
                        },
                        new
                        {
                            Id = new Guid("82d5d9cc-4c1e-4f1c-9fb8-36dacf17e74a"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Water Protection and Engineering"
                        },
                        new
                        {
                            Id = new Guid("aa3867be-3795-46da-8115-c362e885353f"),
                            Description = "Short Description",
                            FacultyId = new Guid("d543979a-8a39-4213-9197-84c29d4cf58a"),
                            Title = "Engineering of gas supply and heating systems, ventilation"
                        },
                        new
                        {
                            Id = new Guid("19841459-7c80-4f42-aa36-9939bef10716"),
                            Description = "Short Description",
                            FacultyId = new Guid("0e2aed9e-99eb-41c4-a3ad-a06bf63459e2"),
                            Title = "Decorative Arts"
                        },
                        new
                        {
                            Id = new Guid("b462bc0c-98c4-4671-9b32-a2a09f0e0eec"),
                            Description = "Short Description",
                            FacultyId = new Guid("0e2aed9e-99eb-41c4-a3ad-a06bf63459e2"),
                            Title = "Engineering and Industrial Technologies"
                        },
                        new
                        {
                            Id = new Guid("667364de-c97a-4602-b879-5e5ccd575feb"),
                            Description = "Short Description",
                            FacultyId = new Guid("0e2aed9e-99eb-41c4-a3ad-a06bf63459e2"),
                            Title = "Textile, clothes, footwear and leather processing"
                        },
                        new
                        {
                            Id = new Guid("a69041e7-c4e3-48a3-8ca2-567012077b89"),
                            Description = "Short Description",
                            FacultyId = new Guid("5ec9f43e-b68c-48cc-a983-1463716f8b03"),
                            Title = "Accounting"
                        },
                        new
                        {
                            Id = new Guid("856db952-8b97-4a10-874e-e376bad8f6cc"),
                            Description = "Short Description",
                            FacultyId = new Guid("5ec9f43e-b68c-48cc-a983-1463716f8b03"),
                            Title = "Marketing and Logistics"
                        },
                        new
                        {
                            Id = new Guid("7cdf0042-9c4f-4a84-8333-0555b87f98a2"),
                            Description = "Short Description",
                            FacultyId = new Guid("5ec9f43e-b68c-48cc-a983-1463716f8b03"),
                            Title = "Business and Administration"
                        },
                        new
                        {
                            Id = new Guid("e001ebdd-895a-4892-8c7b-947284d28258"),
                            Description = "Short Description",
                            FacultyId = new Guid("0f64242d-fda3-4885-8a7f-4624731adfde"),
                            Title = "Law"
                        },
                        new
                        {
                            Id = new Guid("cf6ce58a-d3ea-4901-b9aa-7c0be3a33a80"),
                            Description = "Short Description",
                            FacultyId = new Guid("0f64242d-fda3-4885-8a7f-4624731adfde"),
                            Title = "Engineering and Management in constructions"
                        },
                        new
                        {
                            Id = new Guid("2caecd30-a59a-4134-b5f4-98f32bbac557"),
                            Description = "Short Description",
                            FacultyId = new Guid("0f64242d-fda3-4885-8a7f-4624731adfde"),
                            Title = "Wood processing technology"
                        },
                        new
                        {
                            Id = new Guid("956be74d-9dcd-4cf5-ad79-7fd2a8e9df57"),
                            Description = "Short Description",
                            FacultyId = new Guid("0f64242d-fda3-4885-8a7f-4624731adfde"),
                            Title = "Mining engineering"
                        },
                        new
                        {
                            Id = new Guid("6ce77e0c-2518-4a2b-bba5-2d8be51a1f36"),
                            Description = "Short Description",
                            FacultyId = new Guid("0f64242d-fda3-4885-8a7f-4624731adfde"),
                            Title = "Geodesy, topography and mapping"
                        },
                        new
                        {
                            Id = new Guid("6002480d-37fd-4aea-9162-0fa004b92818"),
                            Description = "Short Description",
                            FacultyId = new Guid("0f64242d-fda3-4885-8a7f-4624731adfde"),
                            Title = "Assessment of Real Estate"
                        },
                        new
                        {
                            Id = new Guid("942aa9c8-3623-4edb-8440-799c5a496b2d"),
                            Description = "Short Description",
                            FacultyId = new Guid("0f64242d-fda3-4885-8a7f-4624731adfde"),
                            Title = "Construction and civil engineering"
                        },
                        new
                        {
                            Id = new Guid("9a7581f6-bbfb-4a2a-a54e-dbf9683223ef"),
                            Description = "Short Description",
                            FacultyId = new Guid("0f64242d-fda3-4885-8a7f-4624731adfde"),
                            Title = "Fire Engineering and Civil Protection"
                        },
                        new
                        {
                            Id = new Guid("f3478051-f593-452b-bd4c-f84539bcab83"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Сomputers and Networks"
                        },
                        new
                        {
                            Id = new Guid("b963a497-8cb4-43ff-9c88-be2c71c24755"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Informational Management"
                        },
                        new
                        {
                            Id = new Guid("7d652683-e8d9-476c-80c5-8f8f9e49c1a7"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Information technology"
                        },
                        new
                        {
                            Id = new Guid("31dba013-0ce5-4a25-8567-7d4d4a097efe"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Informational security"
                        },
                        new
                        {
                            Id = new Guid("79eefef3-3a02-42fb-a740-e92610598b60"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Software Engineering"
                        },
                        new
                        {
                            Id = new Guid("3d1f4d33-f29d-4f10-9a25-535788eb0438"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Applied Informatics"
                        },
                        new
                        {
                            Id = new Guid("303e2855-9f0c-4411-99ff-931c05a0ac48"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Microelectronics and nanotechnologies"
                        },
                        new
                        {
                            Id = new Guid("bca078b6-faa4-4027-9819-8dfeb93fc545"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Automation and Information Science"
                        },
                        new
                        {
                            Id = new Guid("c45c9b75-532a-4e24-9c80-840bf451c386"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Robotics and mechatronics"
                        },
                        new
                        {
                            Id = new Guid("34ae72b1-d57d-4f11-ab90-c1aaa83b7b3e"),
                            Description = "Short Description",
                            FacultyId = new Guid("f3664286-15e9-49e5-b952-c02d744e09db"),
                            Title = "Biomedical systems engineering"
                        },
                        new
                        {
                            Id = new Guid("baa78b6c-2ceb-4347-96d8-ca7d8dff19bd"),
                            Description = "Short Description",
                            FacultyId = new Guid("13f040e8-f953-4eb4-af06-a56501e10ef0"),
                            Title = "Engineering and Management in Telecommunications"
                        },
                        new
                        {
                            Id = new Guid("8ab3849b-4ffa-430d-bab1-53ded21b923f"),
                            Description = "Short Description",
                            FacultyId = new Guid("13f040e8-f953-4eb4-af06-a56501e10ef0"),
                            Title = "Telecommunications technologies and systems"
                        },
                        new
                        {
                            Id = new Guid("bef9fd08-4740-4ba7-bdcc-e074232ec9eb"),
                            Description = "Short Description",
                            FacultyId = new Guid("13f040e8-f953-4eb4-af06-a56501e10ef0"),
                            Title = "Telecommunications networks and software"
                        },
                        new
                        {
                            Id = new Guid("166798c9-720f-4c92-b711-93be29b7089e"),
                            Description = "Short Description",
                            FacultyId = new Guid("13f040e8-f953-4eb4-af06-a56501e10ef0"),
                            Title = "Radio and television communications"
                        },
                        new
                        {
                            Id = new Guid("b8de5904-f002-4737-9e37-568faf92f801"),
                            Description = "Short Description",
                            FacultyId = new Guid("13f040e8-f953-4eb4-af06-a56501e10ef0"),
                            Title = "Applied electronics"
                        },
                        new
                        {
                            Id = new Guid("3f7c0a1c-6adf-4052-8cef-edc084acdffc"),
                            Description = "Short Description",
                            FacultyId = new Guid("41ba4ac4-5991-4977-a134-7c7750095021"),
                            Title = "Technology and management of catering"
                        },
                        new
                        {
                            Id = new Guid("152eb23f-b89a-487a-8b51-55fd57cc1775"),
                            Description = "Short Description",
                            FacultyId = new Guid("41ba4ac4-5991-4977-a134-7c7750095021"),
                            Title = "Technology of Food Production"
                        },
                        new
                        {
                            Id = new Guid("fc2c2dbe-785a-46c3-a58c-98ec292d55fe"),
                            Description = "Short Description",
                            FacultyId = new Guid("41ba4ac4-5991-4977-a134-7c7750095021"),
                            Title = "Technology of Wine and Fermented Products"
                        },
                        new
                        {
                            Id = new Guid("fc103339-1765-40f1-8912-91fd8d35d357"),
                            Description = "Short Description",
                            FacultyId = new Guid("41ba4ac4-5991-4977-a134-7c7750095021"),
                            Title = "Public nutrition services"
                        },
                        new
                        {
                            Id = new Guid("756af7f3-5208-4e15-9f12-dae6f8f17f4f"),
                            Description = "Short Description",
                            FacultyId = new Guid("41ba4ac4-5991-4977-a134-7c7750095021"),
                            Title = "Industrial Biotechnology"
                        });
                });

            modelBuilder.Entity("Unipply.Models.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserData");
                });
#pragma warning restore 612, 618
        }
    }
}
